### ISSUE TITLE
conversational actions not being called.

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [wit-ai/node-wit#1]
Hello,

I am working through the quick start example and dont seem to be receiving back any bot messages. I have created my story exactly how the example illustrates so think it may be my code setup.

It seems that the only way to receive the next actions is through the command line.

my setup is as the example illustrates:

```
const actions = {
          say: (sessionId, msg, cb) => {
            console.log(msg);
            cb();
          },
          merge: (context, entities, cb) => {

              console.log('context ', context, entities );

              const loc = firstEntityValue(entities, 'location');
              if(loc) {
                context.loc = loc;
              }
            cb(context);
          },
          error: (sessionId, msg) => {
            console.log('Oops, I don\'t know what to do.');
          }

    };

this.client = new Wit(this.token, actions);
this.client.interactive();

// sending message
 this.client.message( messageStr, ( ) =>{ } );
```

The code executes with no errors, however I am not receiving a response as illustrated in the example? Am I setting up the code incorrectly? Do I need to change the code to receive the automated bot questions?

Any help would be much appreciated.

Thanks

**Comment by blandinw** [comment]
@theboyWhoCriedWoolf the `.message()` method does not send a message. It allows you to extract entities from one given message.

Could you try removing that last line of code and just run `node index.js` to chat with your bot?
If it doesn't work, could you paste the full output?

**Comment by theboyWhoCriedWoolf** [comment]
Thanks for the response @blandinw.

I am not trying to use this through a CLI.

I want to run in within my server to send and interact with wit.ai messages and responses, allowing me to parse the relevant data and correctly structure each message on the backend before passing the content to whatever client uses the service on the client side.

My node server acts as the gateway between client and wit.ai in order to parse specific data and using external API's as required.

is node-wit able to do this or do I need to use HTTP API directly?

Thanks

**Comment by patapizza** [comment]
If I understand correctly, you need to remove the `.interactive()` (which enables the CLI with your bot) and use the `.runActions()` method each time you receive a message from the user. This method will run your bot automatically, calling your `say` action each time there is a message to send back. `runActions()` will return the updated context in the callback.
The handling of bot messages (parsing, structuring and passing the content to the client) should be done in the `say` action.

Hope this helps.

**Comment by theboyWhoCriedWoolf** [comment]
Amazing thanks @patapizza. I had kind of thought that might be the approach so slightly rewrote the module. Works great. 

Thanks
