### ISSUE TITLE
Confidence Jumps to 2.0416216798903555e-7

### ISSUE THREAD

**Issue by zaal** [wit-ai/node-wit#100]
Hi,
context received by wit is correct, and the branch should've matched correctly, instead of wit responding with action:'msg', it responds with another action with weird confidence:
```
{
    "confidence": 2.0416216798903555e-7,
    "type": "action",
    "action": "settings"
}
```
I have never observed confidence this high :) How can this be? And I also see no reason to why wit should've decided to jump to the other story, when I didn't even reset the session_id.

**Comment by zaal** [comment]
Also, it loops forever between one action to another. Only thing stopping it is the time out of the aws lambda function.

**Comment by stopachka** [comment]
cc @blandinw @patapizza -- any thoughts on why this would happen?

**Comment by zaal** [comment]
Hey @stopachka I forgot to close this one. It was occurring because wit could not find the matching story/branch to execute because at the time, we where experimenting with actions having strict requirements. So Wit would jump from story to story trying to find correct branch to go through, but it couldn't find one and at every step along the way, the confident would explode or diminish.
