### ISSUE TITLE
session id invalid

### ISSUE THREAD

**Issue by bilalbayasut** [wit-ai/node-wit#101]
I've tried many times and correctly , but I get the response saying "session id invalid". I tried it either via postman, terminal and other apps. I don't know what caused it.. before it was fine, please help me , thanks

**Comment by stopachka** [comment]
hey @bilalbayasut, this may be better posted on stackoverflow, with a code snippet. Feel free to ping me your code snippet as well, and I can have a look personally (stopachka@fb.com
