### ISSUE TITLE
Action when no intent detected

### ISSUE THREAD

**Issue by akshaydeshraj** [wit-ai/node-wit#102]
I have 4 intents in my application. There are no entities. The classification of intents is working perfectly. In the Understanding Tab, when I enter a random text that is not relevant to my use case, no intent is detected (as expected). But when this happens in my bot, it runs one of the actions. Is there any way I can define an action for the case when no intent is detected.

I am using `node-wit` with fb messenger

**Comment by toxuin** [comment]
You can try to create a story without an intent tied to it, like a "catch-all" story that would basically fire every time bot does not understands what is going on. Then, in that story, you can call for some action like brainFart().

**Comment by stopachka** [comment]
@toxuin's idea could work. This may be better posted on stackoverflow or the Wit.ai Hackers facebook group

**Comment by nithingit** [comment]
I have created the story for handling catch-all (without intent) but the bot is not executing the corresponding function
