### ISSUE TITLE
"merge" action misundestanding

### ISSUE THREAD

**Issue by trieudh58** [wit-ai/node-wit#103]
I am digging in wit SDK for node.js. And there is one term that I do not understand: "merge" action.
I found it in [POST /converse](https://wit.ai/docs/http/20160526#post--converse-link) API endpoint, but it is not clearly explained: `merge (first bot action after a user message)`

In node.js code (lib/wit.js): 
```javascript
// backwards-compatibility with API version 20160516
if (json.type === 'merge') {
  json.type = 'action';
  json.action = 'merge';
}
```
and:
```javascript
} else if (json.type === 'action') {
  throwIfActionMissing(actions, json.action);
  return actions[json.action](request).then(ctx => {
```

So, `actions[json.action]` here equals to `actions["merge"]`. So what the value of this `actions["merge"]`?

I think that the `actions` object only contains some functions such as `send()` and some other user-defined functions. 

What is exactly "merge" action? Can someone explain it to me? 

Thanks in advance.

**Comment by magnusburton** [comment]
The merge action is deprecated but what it used to do was to take the entities and turn them into context variables.

**Comment by trieudh58** [comment]
@magnusburton so you mean that the current version API will never return `"type": "merge"` as shown in [this HTTP response example](https://wit.ai/docs/http/20160526#post--converse-link) ?
And in previous API versions, we must define a **merge** action in `actions` object?

**Comment by trieudh58** [comment]
I found the **merge** action in the release version 3.3.2

``` javascript
merge(sessionId, context, entities, message, cb) {
  // Retrieve the location entity and store it into a context field
  const loc = firstEntityValue(entities, 'location');
  if (loc) {
    context.loc = loc;
  }
  cb(context);
},
```

Now I understand it. Thank you.
