### ISSUE TITLE
How to stop wit temporarily?

### ISSUE THREAD

**Issue by minhtringo141** [wit-ai/node-wit#108]
I've successfully in intergrating Wit.ai to my fanpage fb messenger. But i want to stop it temporarily so i can directly chat with my user but i don't know how to do that? Anyone can tell me how to? thanks. Or is there any way to stop wit when user types some keyword util trigger it by the 1st sentence in the story?

**Comment by stopachka** [comment]
hey @minhtringo141, You would do this in your application logic. 

You can store some info about the user, and instead of `wit.runActions`, you transfer them to your own UI.

**Comment by MathieuDuboy** [comment]
Can you explain exactly what is the process here please ? I'm not sure I can understand what you said ! Thank you
