### ISSUE TITLE
'Thank you’ being detected as search query always. Even after training it for entity

### ISSUE THREAD

**Issue by newdev7** [wit-ai/node-wit#117]
I have created a new app in wit.ai. In stories, I have created entity with different intents. Here I used 'Thank you' as a different intent. But when I send 'Thank you' to wit, it considers it as a search query instead of the entity which I created. I trained it for that entity in the 'Understanding tab. But still it is considering it as a search query. Like that for some other intent also, it considers as a search query only. What shall I do to make the 'Thank you' string as an entity instead of search query?

Thanks.

**Comment by dispareil** [comment]
i'm also getting wrong output when i use this package. When i use curl with wit.ai http api, it returns the correct output. I have already trained the wit.ai system. when i use the wit.ai console, i get correct output.

**Comment by nemphys** [comment]
What I have noticed in similar situations is that it takes some time for the actual training to be executed (even though the lights are green). Try it again after a few hours and it might work properly.

**Comment by dinesh-chander** [comment]
@newdev7 we faced the same sort of problem and had a conversation with @l5t. He told us
 > wit/search_query is a free text entity not a trait one. In other words, it should not be a intent. I 
> would also recommend not to use it since it is trained across thousands of wit apps and can 
> behave strangely
