### ISSUE TITLE
help getting quickstart.js to run

### ISSUE THREAD

**Issue by dan9thsense** [wit-ai/node-wit#121]
It shouldn't be this hard!
I followed the [quickstart tutorial](https://wit.ai/docs/quickstart).  Got the story working.  Moved on to quickstart.js  Cloned and installed. The first error was a syntax one, solved by adding the flag
` --harmony_destructuring`
to the command line.  I am running node version 4.5.0 LTS and prefer not to upgrade because of other node projects that may not look kindly upon that upgrade.   Next error was 
`node-wit not found`
which was also seen by [sandeepgiri](https://github.com/sandeepgiri), as mentioned in the discussion of issue #55 Unfortunately, there is no explanation there.  I rearranged the directory installations to be a more normal node structure than the tutorial creates and that bug went away.
Now I have another error, this one from wit.js, and I don't know how to solve it.

```
src\node_modules\node-wit\lib\wit.js:193
const runAction = (actions, name, ...rest) => {
                                  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\dan\Dropbox\wit\src\node_modules\node-wit\index.js:3:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by haganbt** [comment]
@dan9thsense - I have nothing to do with this project but had similar issues. That error is likely due to the node version also due to some ES6 goodness not running.

It may be simpler to install something like NVM so you can easily switch between versions. See https://www.sitepoint.com/quick-tip-multiple-versions-node-nvm/

If you do get Node upgraded, you may want to check out https://github.com/wit-ai/witty-weather for a full node.js example (note the example webapp is written with React).

**Comment by dan9thsense** [comment]
Gave up trying to get it to work with node version 4.5.  
@haganbt Took your suggestion; with the upgrade to 7.2.0, it works.
Also, thanks for the link to witty-weather.

Given how hard it is to make work with earlier versions of node, I suggest that the minimum version of node that fully works should be listed as a requirement for the tutorial.
