### ISSUE TITLE
Error: No 'null' action found

### ISSUE THREAD

**Issue by aakashkag** [wit-ai/node-wit#123]
I am running example  quickstart.js 
so i am getting following error 
Error: No 'null' action found

**Comment by thibaultboursier** [comment]
Same problem than #5

**Comment by patapizza** [comment]
We've sunset Bot Engine: https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5
