### ISSUE TITLE
Is there a way to make fetch support cross browser origin access ?

### ISSUE THREAD

**Issue by ghost** [wit-ai/node-wit#125]
I tried to add { mode : 'no-cors' } but it didn't work. There was another issue addressing this. So my option now is to use : 

 Using JSONP with jQuery
`
$.ajax({
  url: 'https://api.wit.ai/message',
  data: {
    'q': 'set an alarm in 10min',
    'access_token' : 'MY_WIT_TOKEN'
  },
  dataType: 'jsonp',
  method: 'GET',
  success: function(response) {
      console.log("success!", response);
  }
});
`
But this doesn't work for converse - POST method of converse. I tried inserting this piece of code in wit.js to try to get it to work :

`
logger.debug(method, fullURL);

    $.ajax({
      url: 'https://api.wit.ai/converse',
      data: {
        'q': qs,
        'access_token': '5EIBODHPO3N45KAEKD3KAKP6A2JB7PJN'
      },
      dataType: 'jsonp',
      method: method,
      success: function(response) {
        console.log(" AJAX JSONP MESSAGE success!", response);
      }
    });

    return fetch(fullURL, {
      method: method,
      headers: headers,
      body: JSON.stringify(context)
    }).then(function(response) {
      return Promise.all([response.json(), response.status]);
    }).then(handler);
  };
`

**Comment by l5t** [comment]
https://github.com/wit-ai/wit/issues/242
