### ISSUE TITLE
Simple action flow not working on localhost

### ISSUE THREAD

**Issue by kyle-ssg** [wit-ai/node-wit#126]
Hi, this may be a miss understanding on my part however I am unable to get a simple action workflow to work. My expectation is that the following would result in the bot responding with "Response is Hi", however the send action never gets called.

Does this mean that actions don't actually get executed when testing from the dashboard?

**My example**:

```
const {Wit, log, interactive} = require('node-wit');
const {witToken} = require('../config');
const client = new Wit({
    accessToken: witToken,
    actions: {
        send(request, response) {
            console.log("SENDING");
            return new Promise(function(resolve, reject) {
                return resolve("Hi");
            });
        }
    },
    logger: new log.Logger(log.DEBUG) // optional
});
```

**My Recipe**
<img src="http://image.prntscr.com/image/6580746d11e04316948438c599ec214b.png"/>

**The Bot**
<img src="http://image.prntscr.com/image/9890e11defe4450fb3e9c9db63dfff0c.png"/>

**Comment by l5t** [comment]
Have you tried with WittyFiddle?https://github.com/wit-ai/witty-fiddle 
It should help you get the right syntax. Basically you would only have res and not {res} in the branch step below the Send action in your story and in your code, you will create a context key like this:
context.res = "hi";

**Comment by kyle-ssg** [comment]
Ah yep I see - will amend that. My main concern is that the action call to ```send()``` or any other action for that matter doesn't hit my server.

**Comment by kyle-ssg** [comment]
Ended up writing facebook messenger implementation to test actions
