### ISSUE TITLE
HTTP API

### ISSUE THREAD

**Issue by hoodsy** [wit-ai/node-wit#127]
Is there an officially supported repo wrapping the HTTP API functions?

If not, I'll be wrapping some requests (e.g. adding expressions to an entity, etc) in a way similar to [twit, a wrapper for the Twitter API](https://github.com/ttezel/twit), and maybe I'll share the project if others would find it useful.

**Comment by l5t** [comment]
cc @blandinw, that would be great!

**Comment by derekmartinez18** [comment]
Any progress on this? If not, I'll go ahead and start working on this as I do need it for one of my projects anyways.

**Comment by hoodsy** [comment]
@derekmartinez18 I wrapped a few of the API endpoints, but it turned out my needs didn't reach anywhere near full coverage. 

Would be happy to contribute to your project if you do something more extensive.

**Comment by derekmartinez18** [comment]
Alright thanks!

I am not quite done planning things out so I am now sure how far my needs will go but I'll see what I can do.
