### ISSUE TITLE
How can I take the message respond with js

### ISSUE THREAD

**Issue by m7vm7v** [wit-ai/node-wit#128]
Hi, in my js I have:

$.ajax({
                  url: 'https://api.wit.ai/message',
                  data: {
                        'q': 'how are you',
                        'access_token' : 'the token'
                  },
                  dataType: 'jsonp',
                  method: 'GET',
                  success: (givenWitAnswer) => {
                        console.log(givenWitAnswer);
                  }
                });

And for the question in  my stories I have 'fine' and when I try to chat with my bot from there it is working.
But in my request the respond is only the entities. The message answer it is not included. How can I get the answer respond from the stories. Thanks

**Comment by ramh** [comment]
Closing old issues, please re-open if you are still facing the issue. Thanks.
