### ISSUE TITLE
TypeError: Cannot read property 'length' of null when I run bot.js on the server

### ISSUE THREAD

**Issue by M-Abozaid** [wit-ai/node-wit#136]
tarting process with command `node index.js`
> string_decoder.js:50
 if (buf.length === 0)

TypeError: Cannot read property 'length' of null
 at StringDecoder.write (string_decoder.js:50:10)
at Interface._normalWrite (readline.js:353:30)
 at Interface.write (readline.js:344:49)
at prompt (/app/node_modules/node-wit/lib/interactive.js:18:8)
 at module.exports (/app/node_modules/node-wit/lib/interactive.js:20:3)

However it runs just fine when i node bot.js on my machine.
can someone help me!

**Comment by chunkitmax** [comment]
According to Interface.write, it will call Interface._normalWrite with null argument if it is not running in the terminal. Therefore, it should be fine in the terminal.

**Comment by juanserra** [comment]
@M-Abozaid I'm having the exact same issue, I wonder if you ever managed to solve it? Thanks

**Comment by juanserra** [comment]
In case it helps anyone, I managed to fix this by replacing `rl.write(null, {ctrl: true, name: 'e'});` for `rl.write('', {ctrl: true, name: 'e'});` on this line https://github.com/wit-ai/node-wit/blob/master/lib/interactive.js#L19. Just replacing the null parameter for an empty string seems to fix the error.

**Comment by patapizza** [comment]
This is related to Bot Engine and stories, which we've deprecated: https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5
