### ISSUE TITLE
Ngrok Command in the instructions

### ISSUE THREAD

**Issue by terekjudi** [wit-ai/node-wit#14]
In the documentation it uses the following command for ngrok  
`./ngrok -http 8445`  
But it should be  
`./ngrok http 8445`

**Comment by bdthinh** [comment]
Yes, I encountered your problem too

**Comment by patapizza** [comment]
Thanks!

**Comment by dnorton94** [comment]
what is ./ngrock http 8445. I type it in the command line I keep getting ...
"." is not recognized as an internal or external command, operable program or batch file
