### ISSUE TITLE
POST /converse gives doesn't work.

### ISSUE THREAD

**Issue by ghost** [wit-ai/node-wit#148]
Hi, when I try to communicate with my bot I am fine with getting intents but when I try to get the respond from the bot, it does not work. How can I get the answer from the bot? I am currently trying the code below. After I use this code it gives "jQuery19007088598059934517_1499850109587(wit the hell?);"

$.ajax({
                url: 'https://api.wit.ai/converse',
                data: {
                    'q': 'Helloo', // The message to send the bot
                    'session_id': '123abc',
                    'access_token': 'MY_TOKEN',
                    
                },
                dataType: 'jsonp',
                crossDomain: true,
                method: 'POST',
                type: 'msg'

                success: function (response) {

                    console.log("Inside converse");
                    console.log(JSON.stringify(response));

                },
                error: function () {

                    console.log("Converse wrong mate :/");
                }
            });

**Comment by patapizza** [comment]
We've sunset converse: https://medium.com/wit-ai/launching-built-in-nlp-for-messenger-and-sunsetting-bot-engine-beta-46e9038869a5.
