### ISSUE TITLE
How to clear variable from context?

### ISSUE THREAD

**Issue by PN9** [wit-ai/node-wit#152]
I am making a webservice call through node and saving the response in a context variable. But for the next further conversations, am getting the web service response as reply from bot. The previously saved variable is not getting cleared from the context. Please help me in how to clear the context.

**Comment by l5t** [comment]
You can look at line 41 here: https://wit-ai.github.io/witty-fiddle/?id=5a387f6ccb4be4a1f77f2113747a558a
That being said, Stories are being deprecated and will shut down on February 1, 2018. Learn more about why and how to migrate here: https://wit.ai/blog/2017/07/27/sunsetting-stories
