### ISSUE TITLE
Invalid JSON response

### ISSUE THREAD

**Issue by Ottunger** [wit-ai/node-wit#154]
Coming back on #153 , I have had the same issue:

> Error from runtime:  SyntaxError: Unexpected token S in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at /home/gregoire/ElectroFox-Chatbot/node_modules/node-fetch/lib/body.js:48:15
>     at process._tickCallback (internal/process/next_tick.js:109:7)

This seems to happen the thirdtime /converse is called with a same conversation ID (ie: the first call to runActions works, the third throws with this error).

But I think this happens because of another error: the second call never returns, and probably this third call creates an exception saying we cannot process several calls at the same time? But I definitely thinkk the error lies in the second call timing out.

I suspect a change server side as my app hasn't changed for a long time now.

**Comment by dderuntz** [comment]
Looks like Fetch is causing this error:

`npm WARN deprecated npm-registry-fetch@1.1.1: this version has a breaking change. use 1.1.0 or upgrade to latest`

**Comment by stopachka** [comment]
@dderuntz /converse is deprecated -- are you having an issue with a different call? If yes, please let me know a quick repro: 
- app id
- request you run

and I'll be happy to take a look!
