### ISSUE TITLE
npm WARN html@1.0.0 No repository field

### ISSUE THREAD

**Issue by robthos** [wit-ai/node-wit#155]
Hello out there,

The title is the issue it all starts with when I run

[root@... html]# npm install --save node-wit

I ignored it and continued with

[root@... html]# node --harmony_destructuring examples/basic.js

and it threw:

node: bad option: --harmony_destructuring

I have checked and the only problem I detected was that Putty shows only 8 out of 64 maps in the node_modules:

drwxr-xr-x  2 root root 4096 Aug 22 10:10 .bin
drwxr-xr-x  4 root root 4096 Aug 22 10:10 encoding
drwxr-xr-x  4 root root 4096 Aug 22 10:10 iconv-lite
drwxr-xr-x  3 root root 4096 Aug 22 10:10 isomorphic-fetch
drwxr-xr-x  2 root root 4096 Aug 22 10:10 is-stream
drwxr-xr-x  4 root root 4096 Aug 22 10:10 node-fetch
drwxr-xr-x  5 root root 4096 Aug 22 10:12 node-wit
drwxr-xr-x  4 root root 4096 Aug 22 10:10 uuid
drwxr-xr-x  2 root root 4096 Aug 22 10:10 whatwg-fetch

I am totally new to Wit, Node, and forums like this so I hope you good folk can address the issues and lead me to the answer.

BR

**Comment by michaelmior** [comment]
@robthos This warning shouldn't actually cause you any problems. It just means that one of the packages this one depends on didn't specify source repository information in its metadata. This isn't necessary for correct installation.
