### ISSUE TITLE
Original values of entities not returned

### ISSUE THREAD

**Issue by MatthiasVervaet** [wit-ai/node-wit#157]
I am working on a chatbot where you can ask the current TV programmation.
I ran into the boundaries of wit regarding the returned values of wit.message.

A user can ask the question to our bot: "when is house?"
This results in a returning object of:
```
{
   title:[
      {
         confidence:0.97304907997389,
         value:'House M.D.',
         type:'value'
      }
   ],
   intent:[
      {
         confidence:0.99991155891758,
         value:'show title'
      }
   ]
}
```

The problem is that i want to match "house" with multiple other shows like: House of Cards, House Rules. This is currently not possible because the original entity value isn't returned.

Improvement proposition: 

```
{
   title:[
      {
         confidence:0.97304907997389,
         value:'House M.D.',
         original: 'house',
         type:'value'
      }
   ],
   intent:[
      {
         confidence:0.99991155891758,
         value:'show title'
      }
   ]
}
```

**Comment by l5t** [comment]
You can use the optional parameter verbose=true to get more info like the body (https://wit.ai/docs/http/20170307#get--message-link)
