### ISSUE TITLE
message context field in wrong format

### ISSUE THREAD

**Issue by maciaswojtas** [wit-ai/node-wit#158]
I am trying to use optional 'context' filed in message GET.

Wit.ai backend accepts only JSON syntax only without quotation. 

Json like this will be accepted
{entities:[{id: yes_no}]}
https://api.wit.ai/message?q=yes&context=%7Bentities%3A%7Bid%3A%20yes_no%7D%7D

But Json like this (sematically valid one)
{entities:[{id: "yes_no"}]} is not accepted
Error code retruned by Wit.ai:
"error": "Invalid json context",
"code": "invalid-context-json"

In node-wit you call JSON.stringify on context field. So it is impossible to send format expected by Wit.ai backend, but fix should be probably made on backend side.

**Comment by lamkent00** [comment]
Hi @maciaswojtas , 
I'm trying use 'context' in GET /message to save value. 
Is there any example about make request from variables which collected from stories of user and chatbot ?
I mean this:
User: show me the weather ?
BOT: where? 
User: Hawaii (var_A)
BOT: When?
User: tomorrow (var_B)
==> collect var_A, var_B, for request information.

I'm try this code but Response didn't came with 'context' value 
CODE: 
`client.message('show me the weather', {context})
.then((entities) => {
	console.log('ENTITIES: '+JSON.stringify(entities));
})
.catch(console.error);`

RESPONSE: 
`ENTITIES: {"msg_id":"0E1VpcBWnYUR4xpJh","_text":"show me the weather","entities":{"QuestionType":[{"confidence":0.89924784861561,"value":"weather","type":"value"}],"task":[{"confidence":0.99296915913909," value":"show_weather","type":"value"}]}}`

Can you give me some suggest ?
Thanks so much :)

**Comment by maciaswojtas** [comment]
I belive it is not related with context of message GET function. 

What you want to do? You want to store in context that user asked for Hawaii and tomorrow?

**Comment by lamkent00** [comment]
@maciaswojtas yes. I want to store value in context ( hawaii, tomorrow)
Can you suggest me how to do that or an example  to do with /message

**Comment by l5t** [comment]
https://github.com/wit-ai/node-wit/issues/160#issuecomment-330977368

**Comment by maciaswojtas** [comment]
Laurent issue reported by me is still not resolved. 

It is imposible to make /message GET with entity property in context.
