### ISSUE TITLE
Solution for [wit] [converse] Error: Model not found (404) in 2017 ?

### ISSUE THREAD

**Issue by lamkent00** [wit-ai/node-wit#160]
Hi everyone,
I'm try to running messenger.js and get error: 
`[wit] [converse] Error: Model not found (404)`
Google tell me must create a story for bot. 
But it was solusion in 2016. For now, WIT notification Stories and POST /converse have been deprecated. This will break in February 2018!
==> So, anyone can help me to pass it plz ? any solusion for this problem in 2017 ?

**Comment by l5t** [comment]
You're right we are deprecating Stories. Do you get the same error when curling directly your app: https://wit.ai/docs/http/20170307#post--converse-(deprecated)-link
If so can you share your App ID

**Comment by lamkent00** [comment]
Hi @l5t
My app id
I'm trying use 'context' in GET /message to save value.
Is there any example about make request from variables which collected from stories of user and chatbot ?
I mean this:
User: show me the weather ?
BOT: where?
User: Hawaii (var_A)
BOT: When?
User: tomorrow (var_B)
==> collect var_A, var_B, for request information.

**Comment by lamkent00** [comment]
Hi @l5t
My app id: 59bd1a67-53db-4c92-9a4c-f9cbebba24e7
I'm trying use 'context' in GET /message to save value.
Is there any example about make request from variables which collected from stories of user and chatbot ?
I mean this:
User: show me the weather ?
BOT: where?
User: Hawaii (var_A)
BOT: When?
User: tomorrow (var_B)
==> collect var_A, var_B, for request information.

**Comment by l5t** [comment]
/message is not Stories. You will have to manage this on your side. When you ask the question "where" you will have to store the answer in your code 
https://github.com/wit-ai/wit/issues/737
