### ISSUE TITLE
N-Best feature with Node wit.message()

### ISSUE THREAD

**Issue by MathieuDuboy** [wit-ai/node-wit#162]
I want to deal with the N-Best feature. In this file [shared.js](https://github.com/wit-ai/wit-api-only-tutorial/blob/master/shared.js), I can see that function is sending an N argument in the API call to /message.
```
function queryWit(text, n = 1) {
  return fetch(
    `https://api.wit.ai/message?v=20170307&n=${n}&q=${encodeURIComponent(text)}`,
    {
      headers: {
        Authorization: `Bearer ${NEW_ACCESS_TOKEN}`,
        'Content-Type': 'application/json',
      },
    }
  ).then(res => res.json());
}
```
Can I deal with N-Best feature with Node and .message() ?
```
const client = new Wit({accessToken: 'MY_TOKEN'});
client.message('what is the weather in London?', {})
.then((data) => {
  console.log('Yay, got Wit.ai response: ' + JSON.stringify(data));
})
.catch(console.error);
```
Thanks

**Comment by l5t** [comment]
client.message('what is the weather in London?', {},N) should work. See here:
https://github.com/wit-ai/node-wit/blob/b05a425382d86dedadee6da26637b68dffdccabd/lib/wit.js#L24
