### ISSUE TITLE
incomplete node-wit package.json

### ISSUE THREAD

**Issue by chris247474** [wit-ai/node-wit#165]
Whenever i try to call interactive from require('node-wit'), i get an error that some module is missing. It seems something may be deprecated here, though I arrived at this repo from the wit.ai official docs. 

First, I got an error saying the 'readline' package didn't exist in node-wit, so I added it myself. Then, i got 

> TypeError: readline.createInterface is not a function" from interactive.js: 8

Can anyone help please? Thanks!

*If it helps, im trying to call the Wit.ai API without using an FB Messenger bot

**Comment by mrshahidlatif** [comment]
I also got the similar problem. But it was resolved when I installed the `readline `module.
