### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by asharpp** [wit-ai/node-wit#166]
I am not getting response from wit,it is showing connection timeout as below, why it's happening so much times.

[wit][debug] GET https://api.wit.ai/message?q=Hi
{ FetchError: request to https://api.wit.ai/message?q=Hi failed, reason: connect ETIMEDOUT 66.220.156.2:443
    at ClientRequest.<anonymous> (/home/ubuntu/CLBot/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://api.wit.ai/message?q=Hi failed, reason: connect ETIMEDOUT 66.220.156.2:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }

**Comment by joechoi-git** [comment]
We are experiencing the same issue. It seems to happen intermittently, but still at a quite severe rate.

Is there any resolution to this?

------------------------------------------------------------
Wit.ai error {"name":"FetchError","message":"request to https://api.wit.ai/message?q=room&context=%7B%22timezone%22%3A%22America%2FNew_York%22%7D failed, reason: connect ETIMEDOUT 66.220.156.2:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"}
0|index    | Wit.ai interpretation room America/New_York { FetchError: request to https://api.wit.ai/message?q=room&context=%7B%22timezone%22%3A%22America%2FNew_York%22%7D failed, reason: connect ETIMEDOUT 66.220.156.2:443
0|index    |     at ClientRequest.<anonymous> (/opt/node/rgabot/node_modules/node-fetch/index.js:133:11)
0|index    |     at emitOne (events.js:96:13)
0|index    |     at ClientRequest.emit (events.js:191:7)
0|index    |     at TLSSocket.socketErrorListener (_http_client.js:358:9)
0|index    |     at emitOne (events.js:96:13)
0|index    |     at TLSSocket.emit (events.js:191:7)
0|index    |     at emitErrorNT (net.js:1279:8)
0|index    |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
0|index    |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
0|index    |   name: 'FetchError',
0|index    |   message: 'request to https://api.wit.ai/message?q=room&context=%7B%22timezone%22%3A%22America%2FNew_York%22%7D failed, reason: connect ETIMEDOUT 66.220.156.2:443',
0|index    |   type: 'system',
0|index    |   errno: 'ETIMEDOUT',
0|index    |   code: 'ETIMEDOUT' }

**Comment by asharpp** [comment]
https://github.com/wit-ai/wit/issues/885
