### ISSUE TITLE
message.nlp.entities not clearing old messages and failing to recognize current message from user

### ISSUE THREAD

**Issue by samt07** [wit-ai/node-wit#168]
Hi 

In my app, after some time, the message.nlp.entities keep printing out values from very old messages which the user had asked. Is there a way to clear old messages or is there some setting in FB apps? I have tried to subscribe and unsubscribe to the facebook page I am using and also tried to reset the Built In NLP token few times. It doesnt seem to have resolved the issue. Please help. The more worrying this is that it keeps sending back that message continuously even when the user doesn't attempt to send any further messages.

**Comment by stopachka** [comment]
Hey @samt07 , if you could provide a repro for us, it would help debug quite a bit. 

- Could you include:
  - Your app id (both wit.ai and token)
  - Minimal steps we can take to repro this behavior:
    - i.e send the following phrases: "A", "B", "C", notice that the entities on "C" are from "A"
  - If possible, also show me the code of where you are printing message.nlp.entities (you can email it at stopachka [at] fb [dt] com

**Comment by samt07** [comment]
Hello 

Thank you very much for responding. Apologies for not giving enough details. However, while continuing to debug, I have found a mistake in my code. This issue is not occurring after I fixed the bug. I will close this now and continue to work on my app. I will reach out by raising a new issue if I get stuck up again. Thanks for your time.

**Comment by l5t** [comment]
No worry!
