### ISSUE TITLE
Wit.message() method doesn't support msg_id param

### ISSUE THREAD

**Issue by pintux** [wit-ai/node-wit#169]
Method [Wit.message() ](https://github.com/wit-ai/node-wit/blob/master/lib/wit.js) doesn't support sending msg_id param, as provided by HTTP API [/message](https://wit.ai/docs/http/20160511#get--message-link).

**Comment by pintux** [comment]
simple to add, in lib/wit.js --> Wit.message():

```javascript
this.message = (message, context, msgId) => {
...
if (msgId) {
      qs += `&msg_id=${encodeURIComponent(msgId)}`;
}
...
```

**Comment by jtliao** [comment]
merging with #189
