### ISSUE TITLE
Send Response to bot from webservice in a table format

### ISSUE THREAD

**Issue by samt07** [wit-ai/node-wit#170]
Hi all
Is it possible to send a response in a table format. I m using Facebook's Custom NLP messenger to integrate wit.ai app and nodejs for webservice. Looking to achieve something like this but in a tabular format:

Name | ABC Ltd
Location | THRBR, OL
Capacity | 500 Cu Ft
Manufactured | DOUJT

Any help please?

**Comment by l5t** [comment]
No sure we can help here. Wit can help with detection. as for managing the conversation and format of the answers, you will have to rely on your code + Messenger S/R api: https://developers.facebook.com/docs/messenger-platform/reference/send-api
