### ISSUE TITLE
For wit/datetime submitting hh:mm (AM/PM) returns multiple datetime values via API

### ISSUE THREAD

**Issue by stroupaloop** [wit-ai/node-wit#172]
The wit.ai dashboard logs will indicate only one returned value for the datetime JSON object when using the `hh:mm (AM/PM)` format, but when using the API, it returns 3 values in the format, see below:

original text: `Remind me to <do something> at 12:45AM`

wit.ai Logs return: 
```
"datetime": [
   {
      "confidence": 1
      "start": 14
      "end": 24
      "body": "at 12:45AM"
      "value": {
          "value": "2017-12-26T00:45:00.000-05:00"
      }
      "entity": "datetime"
   }
]
```

Actual API logs return:
```
"datetime": [
            {
                "confidence": 1,
                "values": [
                    {
                        "value": "2017-12-26T00:45:00.000-05:00",
                        "grain": "minute",
                        "type": "value"
                    },
                    {
                        "value": "2017-12-27T00:45:00.000-05:00",
                        "grain": "minute",
                        "type": "value"
                    },
                    {
                        "value": "2017-12-28T00:45:00.000-05:00",
                        "grain": "minute",
                        "type": "value"
                    }
                ],
                "value": "2017-12-26T00:45:00.000-05:00",
                "grain": "minute",
                "type": "value"
            }
        ]
```

This makes logic hack-y as the only identifier between actual datetime ranges is confidence, but I don't think that covers all the use cases.

**Comment by patapizza** [comment]
Hi @stroupaloop,

`wit/datetime` returns one single value under `value`, and up to 3 values under `values` when the sentence context is not enough to resolve it to a single value (see the [Entities Format](https://wit.ai/docs/http/latest) section of the API docs). To be clear, the logs are not showing the extra `values` key sent in the API.
