### ISSUE TITLE
i cant extract child intent value

### ISSUE THREAD

**Issue by nickthejagger** [wit-ai/node-wit#175]
how to get `true city value destination` ?

```"entities": {
      "origin": [
        {
          "entities": {
            "true_city_value_destination": [
              {
                "confidence": 0.96017191704743,
                "value": "bali",
                "type": "value"
              }
            ]
          },
          "confidence": 0.99490671495703,
          "value": "6",
          "type": "value"
        }```

**Comment by patapizza** [comment]
Hi @nickthejagger,

One way to do this in Javascript: `x.origin[0].entities['true_city_value_destination']`.

More information:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects
