### ISSUE TITLE
How to run joke bot example?

### ISSUE THREAD

**Issue by christianortega123** [wit-ai/node-wit#177]
I ran `node examples/joke.js $TOKEN` but the bot won't say anything other than `I can tell jokes! Say 'tell me a joke about tech'!` I also have no clue which access token to use. The access token above is just one from one of my apps on wit. 

Thanks!

**Comment by christianortega123** [comment]
Nevermind I didn't realize it used terminal

**Comment by BenBergman** [comment]
This took me a long time to figure out too. The example folders have some .zip files. You need to create a new app in Wit.ai and near the bottom is a "browse" button that lets you upload a backed up app. Once you have created your app, go into the settings and copy out the Server Access Token to run your app.

**Comment by geoqpcr** [comment]
I have the same issue. I tried to import an example and I get a 500 HTTP error on my console.

**Comment by blandinw** [comment]
Looking into it

**Comment by blandinw** [comment]
1) We had a bug in our import flow for this .zip file, the fix will roll out today so you should be able to import the `wit-example-joke-bot.zip` file again
2) I will make a couple changes to README.md and the example .js files to make it clearer that you should import the app to be able to run the examples. Let me know if you have ideas as to how to make it even clearer.
