### ISSUE TITLE
POST /samples (Train Your App) doesn't work how the Understanding Tab works

### ISSUE THREAD

**Issue by eorroe** [wit-ai/node-wit#185]
I'm using the POST `/samples` endpoint to train my app

In the Understanding tab I can highlight any text and tie it to an entity that doesn't match the text

For example

"wait time for lil frankies"

Where "lil frankies" is the text and the entity I tie it to is `restaurant_code` with value "lilfrank"

In the POST `/samples` endpoint I can only train the entity `restaurant_code` with a value of of the original text "lil frankies" and not "lilfrank".

I get a 400/500 status code when doing so, can this be fixed so I can train the text "wait time for lil frankies" but use the entity value "lilfrank"

**Comment by blandinw** [comment]
@eorroe I could not reproduce your issue.
In your example, you should set `value` to `lilfrank`, then set `start` and `end` so that they correspond to the piece of text that is a synonym of `lilfrank` (i.e. "lil frankies"). In your example, it means `start` should be 14 and `end` should be 26.
See our HTTP docs for more info: https://wit.ai/docs/http

**Comment by eorroe** [comment]
Hey I'm doing so, could you please take a look at my code and the results below:

![screen shot 2018-11-07 at 6 20 52 pm](https://user-images.githubusercontent.com/6982605/48167558-088c3180-e2ba-11e8-97fb-502ab554fa29.png)

### wit-ai.js
![screen shot 2018-11-07 at 6 23 59 pm](https://user-images.githubusercontent.com/6982605/48167618-4ab57300-e2ba-11e8-84b8-5993a580af01.png)

# Results
```JSON
{
    "url": "https://api.wit.ai/samples?v=20170307",
    "status": 400,
    "statusText": "Bad Request",
    "headers": {
        "_headers": {
            "content-type": [
                "application/json"
            ],
            "access-control-allow-origin": [
                "*"
            ],
            "access-control-allow-credentials": [
                "true"
            ],
            "x-content-type-options": [
                "nosniff"
            ],
            "date": [
                "Wed, 07 Nov 2018 23:28:59 GMT"
            ],
            "server": [
                "proxygen"
            ],
            "connection": [
                "close"
            ],
            "content-length": [
                "80"
            ]
        }
    },
    "ok": false,
    "body": {
        "_readableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "buffer": {
                "head": null,
                "tail": null,
                "length": 0
            },
            "length": 0,
            "pipes": null,
            "pipesCount": 0,
            "flowing": null,
            "ended": false,
            "endEmitted": false,
            "reading": false,
            "sync": false,
            "needReadable": true,
            "emittedReadable": false,
            "readableListening": false,
            "resumeScheduled": false,
            "emitClose": true,
            "destroyed": false,
            "defaultEncoding": "utf8",
            "awaitDrain": 0,
            "readingMore": false,
            "decoder": null,
            "encoding": null
        },
        "readable": true,
        "_events": {},
        "_eventsCount": 6,
        "_writableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "finalCalled": false,
            "needDrain": false,
            "ending": false,
            "ended": false,
            "finished": false,
            "destroyed": false,
            "decodeStrings": true,
            "defaultEncoding": "utf8",
            "length": 0,
            "writing": false,
            "corked": 0,
            "sync": true,
            "bufferProcessing": false,
            "writecb": null,
            "writelen": 0,
            "bufferedRequest": null,
            "lastBufferedRequest": null,
            "pendingcb": 0,
            "prefinished": false,
            "errorEmitted": false,
            "emitClose": true,
            "bufferedRequestCount": 0,
            "corkedRequestsFree": {
                "next": null,
                "entry": null
            }
        },
        "writable": true,
        "allowHalfOpen": true,
        "_transformState": {
            "needTransform": false,
            "transforming": false,
            "writecb": null,
            "writechunk": null,
            "writeencoding": null
        }
    },
    "bodyUsed": false,
    "size": 0,
    "timeout": 0,
    "_raw": [],
    "_abort": false
}
```

**Comment by blandinw** [comment]
You are receiving a 400 status back, which means your request is malformed.
There's usually information about what the issue is in the response body.

**Comment by eorroe** [comment]
Any idea what that is based off the body I posted and sometimes I get 500

**Comment by eorroe** [comment]
Hey @blandinw could really use some quick help on this, I just need help with this, I don’t understand the response error.

If you could show me some code that does what I need, would be highly appreciated

**Comment by patapizza** [comment]
As 400s are due to a malformed request, the server response body doesn't necessary contain the information to debug. There's likely an issue in the JS code to make the request.
We don't have the bandwidth to help with specific client-side libraries and code.
Thank you for your understanding.
