### ISSUE TITLE
Include datetime body in response?

### ISSUE THREAD

**Issue by stroupaloop** [wit-ai/node-wit#186]
In the wit.ai platform, the `datetime` entity contains `body` but not in the standard node-wit response.

Example:
```
var {Wit, log} = require ('node-wit');

const witClient = new Wit({
    accessToken: SOMETHING
});

witClient.message("check this in 3m").then((data) => {
    console.log(data.entities);
}
```

**Comment by patapizza** [comment]
Hey @stroupaloop, please use the `wit` folder for issues related to the API. This one is for the Node.js SDK.
To get the body, pass in a `verbose=true` flag in your API request: https://wit.ai/docs/http/latest#get__message_link

**Comment by stroupaloop** [comment]
hi @patapizza a bit confused by your response. I see where you add `verbose=true` to a `curl` request. Can you help clarify where it'd go in a node.js request using the Node.js SDK? (updated initial comment with sample code).

**Comment by patapizza** [comment]
Hi @stroupaloop, it wasn't clear that the question was related to the Node.js SDK.
You can pass it as 4th parameter: https://github.com/wit-ai/node-wit/blob/master/lib/wit.js#L28

**Comment by stroupaloop** [comment]
hi @patapizza thanks for the update, seemingly I may be missing something here. Please see below to confirm. After reviewing the blob you sent on the `message` function, I assumed I could pass the following

```
witClient.message("check this in 3m", {timezone: 'America/New_York'},null,false).then((data) => {
	console.log(data);
	console.log('\n');
	console.log(data.entities);
	console.log('\n');
	console.log(data.entities.datetime[0].values)
})
```

but this returns

```
{ _text: 'check this in 3m',
  entities: { reminder: [ [Object] ], datetime: [ [Object] ] },
  msg_id: '135Iuzv3pzV2xJyNq' }


{ reminder: 
   [ { suggested: true,
       confidence: 0.936795,
       value: 'check this',
       type: 'value' } ],
  datetime: 
   [ { confidence: 1,
       values: [Array],
       value: '2018-11-23T14:33:45.000-05:00',
       grain: 'second',
       type: 'value' } ] }


[ { value: '2018-11-23T14:33:45.000-05:00',
    grain: 'second',
    type: 'value' } ]
```

whether using a `true` or `false` value, the returned `datetime` data remains the same, noting the `value` is the converted time vs the original text identified from the string to produce the value like the `reminder` data. 

I'd expect the `value` to be 3m, which is similar to what is shown on the wit.ai dashboard, but seems like it jumps a step to the processed value instead.

Appreciate all the help to clarify as I seemingly may be missing something.

**Comment by aforaleka** [comment]
hey @stroupaloop, what does witClient.message("check this in 3m", {timezone: 'America/New_York'}, null, true) returns? I could not repro your problem when I set the 4th parameter as true, and you should get a response like so:

```
{ datetime:
   [ { confidence: 1,
       values:
        [ { value: '2018-11-23T17:41:57.000-05:00',
            grain: 'second',
            type: 'value' } ],
       value: '2018-11-23T17:41:57.000-05:00',
       grain: 'second',
       type: 'value',
       _entity: 'datetime',
       _body: 'in 3',
       _start: 11,
       _end: 15 } ] }
```

**Comment by stroupaloop** [comment]
resolved the issue, was a versioning issue (was using `4.3.0` vs the updated `5.0.0`). Seems to be properly functioning, thanks!
