### ISSUE TITLE
error executing quickstart.js

### ISSUE THREAD

**Issue by husseinshaib** [wit-ai/node-wit#20]
hello, I have been trying to run the quickstart.js but always fails with error:
`Executing merge action
C:\Users\username\node_modules\node-wit\lib\wit.js:161
        this.converse(
            ^
TypeError: Cannot read property 'converse' of undefined
    at C:\Users\username\node_modules\node-wit\lib\wit.js:161:13
    at Object.actions.say.merge (C:\Users\username\quickstart.js:41:5)
    at null.<anonymous> (C:\Users\username\node_modules\node-wit\lib\wit.js
:230:22)
    at C:\Users\username\node_modules\node-wit\lib\wit.js:32:9
    at process._tickCallback (node.js:355:11)`

I have installed all the dependencies. Any idea? I am stuck at this point and don't know what to do to solve this issue.

Thanks in advance

**Comment by DiegoRBaquero** [comment]
Hi, which version of node are you using?

**Comment by husseinshaib** [comment]
hi,
the issue was solved after upgrading to node 5.
Thank you.

**Comment by l5t** [comment]
Cool. Closing.
