### ISSUE TITLE
Node-wit not returning Sub-Entities

### ISSUE THREAD

**Issue by alextford11** [wit-ai/node-wit#200]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug

**What is the current behaviour?**

node-wit is not returning any sub-entities. curl works fine like how it should.

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

My app is trained to return a string like "Change background to Blue" to:

- Change background (entity)
   - background (sub-entity)
- to Blue (entity)
   - Blue (sub-entity)

but node-wit only returns this:

- Change background (entity)
- to Blue (entity)

Also, this also shows in the wit v2 app on the understanding tab. Sending with `client.message("...")` 
doesn't produce sub-entities but using curl works fine. 

**What is the expected behaviour?**

above

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

180644303313007

**Comment by patapizza** [comment]
Hi @alextford11,

I can't repro this:
<img width="960" alt="Screen Shot 2020-06-04 at 2 06 24 PM" src="https://user-images.githubusercontent.com/1015208/83810217-9d106e80-a66c-11ea-8b62-2c3c3c318a5b.png">

Curious why do you need `action` and `target`? At first glance it seems like the intent, `target_element` and `target_colour` would be enough.
