### ISSUE TITLE
Something went wrong after 200req/m

### ISSUE THREAD

**Issue by dgslv** [wit-ai/node-wit#207]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about node-wit?**
Question
**What is the current behavior?**

After reaching 200req/m+ I'm receiving the following error:
[wit] [message] Error: Something went wrong. We've been notified
I would like to know if there's any API limit and how could I increase it for my app.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

I would expect to receive the intent from the message

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

2187877334578115

**Comment by ChrisyShine** [comment]
We impose rate limits to lighten the load on our systems.
Could you please email help@wit.ai and provide more details about why your use case requires a higher rate?
