### ISSUE TITLE
Having trouble getting the context to send location when integrating with Messenger

### ISSUE THREAD

**Issue by xmas** [wit-ai/node-wit#21]
Hi!

I'm playing around with Messenger integration and having trouble getting the "loc" context variable to get correctly passed using the "messenger.js" example. It works correctly using the same method in "quickstart.js" on the interactive client.

I've noticed a lot of changes recently, has something changed in messenger.js that would cause the context to get lost?

Thanks!

**Comment by obinschoudhary** [comment]
Hi xmas,

i can get "quickstart.js" working but "messenger.js" throws "404 not found". 

Could you please guide me where i can possibly be going wrong?

i checked other app with messenger webhook which is running fine.

**Comment by obinschoudhary** [comment]
Hi @xmas 

i can get "quickstart.js" working but "messenger.js" th§rows "404 not found". 

Could you please guide me where i can possibly be going wrong?

i checked other app with messenger webhook which is running fine.

**Comment by obinschoudhary** [comment]
it seems webhook callback url is giving 404 not found error for messenger.js. Any suggestions here?

**Comment by patapizza** [comment]
@xmas Did you update the `actions` object in `messenger.js` to reflect the one in `quickstart.js`?

@obinschoudhary Please open a new issue for your problem.

**Comment by husseinshaib** [comment]
I have integrated wit.ai with messenger recently and there is no problem at all. You must be missing some configurations.

**Comment by obinschoudhary** [comment]
thanks @patapizza , @husseinshaib. Messenger.js is working now. @hunkim setup was very helpful.
