### ISSUE TITLE
request is deprecated for a year

### ISSUE THREAD

**Issue by oliverjessner** [wit-ai/node-wit#212]
Is there any chance that wit-ai will port this to a more up to date
xhr libary like https://www.npmjs.com/package/node-fetch?

EDIT: As far as I understand the code it's not used anymore. Deleting the dependency would help us all getting better npm audits.

**Comment by oliverjessner** [comment]
Thank you very much. Only thing left todo is publish via npm 😇

**Comment by chessai** [comment]
Publishing will happen Tuesday.

Thanks for reporting!
