### ISSUE TITLE
Voice support?

### ISSUE THREAD

**Issue by SpeedyCraftah** [wit-ai/node-wit#217]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about node-wit?** Question.

Is there support for voice recognition?

**Comment by FengyangZhang** [comment]
Hi @SpeedyCraftah, we have the [POST /speech endpoint](https://wit.ai/docs/http/20200513/#post__speech_link) to extract from audios. We don't have it in the plan to support it on the UX, but feel free to submit a PR

**Comment by SpeedyCraftah** [comment]
Thank you, I'll be happy to do that 😄.
