### ISSUE TITLE
I am trying to delete the app 980230652436692 for over a year

### ISSUE THREAD

**Issue by oliverjessner** [wit-ai/node-wit#222]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about node-wit?**
I am reporting a bug

**What is the current behavior?**
"Something went wrong. We've been notified" 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Click on "Permanently delete this App"

**Comment by ChrisyShine** [comment]
@oliverjessner Our log shows the error message: "You cannot delete your only app". Can you double check if 980230652436692 is the only app that owned by you? You may be the contributor of other apps, but our deletion logic ensures that you have at least one app that owned by you. 
If you really want to delete 980230652436692, can you create a new app and try the deletion of 980230652436692 again?

**Comment by oliverjessner** [comment]
Its my only app, didn't know that. Will try later. 

Thank you very much
