### ISSUE TITLE
Speech Recognition Examples

### ISSUE THREAD

**Issue by dzlandis** [wit-ai/node-wit#234]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about node-wit?**
Question/Feature

Hey there, I was wondering if it would be possible to get some examples of the newly implemented /speech for node-wit. Thanks!

**Comment by patapizza** [comment]
Hey @dzlandis, take a look at [interactive.js](https://github.com/wit-ai/node-wit/blob/main/lib/interactive.js#L53).

**Comment by dzlandis** [comment]
Any instructions on how to run it @patapizza? I can't get it to run. Also, shouldn't it be in the "examples" folder if its an example?

**Comment by dzlandis** [comment]
I was looking for some examples specifically for real time live transcription and making that work.
