### ISSUE TITLE
inference error in the wit api using the npm module v4.2.0

### ISSUE THREAD

**Issue by unixguru2k** [wit-ai/node-wit#235]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about node-wit?**
getting an error from the wit api

**What is the current behavior?**
Getting an error from the Wit API

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[wit] [message] Error: Something went wrong. We've been notified
2022-07-08T15:39:48.083Z - error:   [
  "Oops! Post failed, got an error from wit: Something went wrong. We've been notified, msg: play"
] Line: <anonymous>
no events found from wit

**What is the expected behavior?**
The inference should work

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1507185375968669

**Comment by patapizza** [comment]
Hi @unixguru2k, thanks for reporting. We're actively working on this - tracking: https://github.com/wit-ai/wit/issues/2480
