### ISSUE TITLE
[Bug] Random inference errors while calling wit.message()

### ISSUE THREAD

**Issue by unixguru2k** [wit-ai/node-wit#236]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about node-wit?**
Getting an error on inference while calling wit.message()

**What is the current behavior?**
[wit] [message] Error: Something went wrong. We've been notified
2022-07-28T08:49:30.929Z - error:   [
  "Oops! Post failed, got an error from wit: Something went wrong. We've been notified, msg: score"
] 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Happening on random messages.

**What is the expected behavior?**
The intent should be detected appropriately as it has been in the recent past.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1507185375968669

**Comment by yuzh174** [comment]
Hi @unixguru2k, I see most of your requests actually succeeded. There were just 4 message requests failed as of yesterday. 
Does the same utterance consistently fail? or It just fails randomly?

**Comment by unixguru2k** [comment]
> Hi @unixguru2k, I see most of your requests actually succeeded. There were just 4 message requests failed as of yesterday. Does the same utterance consistently fail? or It just fails randomly?

Hi @yuzh174 - apologies just saw this message.
In some cases, the calls don't fail but the inference is missing the entities that are already annotated.

**Comment by unixguru2k** [comment]
hi @yuzh174 - i think i figured this out, the format of the api response has changed causing inference rule issues.
What would be awesome is if we could get email alerts in such cases to avoid confusion.
Closing the issue for now.
