### ISSUE TITLE
Disabling the signature check to allow babel async/await

### ISSUE THREAD

**Issue by duffmeister** [wit-ai/node-wit#27]
Hey there,

We use babel/bluebird to allow the use of async/await patterns for promise resolution. Unfortunately this transpiling step changes the method signature for our Wit actions and the app fails. We'd like to retain this ability, 

One possible solution is allowing an environment variable to disable the signature check in your `validateActions` method before the argument length is validated.

`if(process.env.DISABLE_WIT_SIGNATURE_CHECK){`
`logger.warn("Signature checks for your app's actions are disabled. Unless you are performing async/await calls please re-enable");`
`return actions;`
`}
`

**Comment by patapizza** [comment]
Hey @duffmeister,

OK let's do a warning instead of throwing an exception.

**Comment by duffmeister** [comment]
You want me to submit a PR?

**Comment by duffmeister** [comment]
https://github.com/wit-ai/node-wit/pull/36

**Comment by patapizza** [comment]
Great, thanks!
