### ISSUE TITLE
Which terminal to use for making node.js client.

### ISSUE THREAD

**Issue by aakash1492** [wit-ai/node-wit#28]
Hey i am new to node.js , can anyone tell in which terminal we have to these steps further. 
**## clone the Node.js client and install Node dependencies:**

**Comment by patapizza** [comment]
Hey,

Any terminal would do. What OS are you running?

**Comment by aakash1492** [comment]
HEY i researched it
i got to know aftr using node js software it can be done.
thanks a lot for replying. :)

**Comment by patapizza** [comment]
You're welcome!
