### ISSUE TITLE
ReadMe#message needs fixin

### ISSUE THREAD

**Issue by teddis** [wit-ai/node-wit#33]
The code snippet is out of date wrt to the API. Should remove the context and read:

```
client.message('what is the weather in London?', (error, data) => {
  if (error) {
    console.log('Oops! Got an error: ' + error);
  } else {
    console.log('Yay, got Wit.ai response: ' + JSON.stringify(data));
  }
});
```

**Comment by patapizza** [comment]
Since version 3.3.0, we added back an optional context parameter as second argument.
See https://github.com/wit-ai/node-wit/commit/be0130ba7210a9e4c55a5c7262f366cb602db52b
