### ISSUE TITLE
Very odd results when passing a session id starting with '/#'

### ISSUE THREAD

**Issue by olivierlesnicki** [wit-ai/node-wit#42]
Very odd results when passing a session id starting with '/#'. I'm using socket.io to create a bot on top of node-wit. Sadly when I pass the socket.id (which starts with /#) to the wit instance as as sessionId I get crazy results coming back.

**Comment by patapizza** [comment]
Can you give a little bit more details? An example of unexpected results would be great.

**Comment by olivierlesnicki** [comment]
If the session id starts with the following characters: '/#'. The runActions do not work.

**Comment by brunocascio** [comment]
@olivierlesnicki 
hash params will not be sent to the server. (https://stackoverflow.com/questions/3664257/why-the-hash-part-of-the-url-is-not-in-the-server-side)
