### ISSUE TITLE
TypeError: Wit is not a constructor

### ISSUE THREAD

**Issue by chandrasekhar4u** [wit-ai/node-wit#44]
While using code in [messenger.js](https://github.com/wit-ai/node-wit/blob/master/examples/messenger.js) or [wit.ai documentation](https://wit.ai/docs/quickstart) as below,

```
// Setting up our bot
const wit = new Wit(WIT_TOKEN, actions);
```

> Getting error like "**TypeError: Wit is not a constructor**"

How to solve this issue, why can't we use this code?

**Comment by patapizza** [comment]
What version of node-wit and node are you using?

**Comment by trylovetom** [comment]
I have the same problem.
I use the node v9.4.0

**Comment by patapizza** [comment]
@trylovetom What is your code? Are you importing `Wit`? Did you install `pywit` through `pip` or the repo?

**Comment by trylovetom** [comment]
I use the node-wit. Run the example code which written in the readme.md. Is pywit required?

**Comment by blandinw** [comment]
@trylovetom pywit is not required, @patapizza probably meant `node-wit` and `npm`.

This is working fine for me, I cannot reproduce your issue. Have you run `cd path/to/node-wit && npm install && npm install body-parser express request` before running `node examples/messenger.js` ?
