### ISSUE TITLE
Error when I try npm install node-wit

### ISSUE THREAD

**Issue by vanni77** [wit-ai/node-wit#45]
I try npm install node-wit when I 'm connected to various networks but I have the same error:

WI0035947P:node-wit vcasari$ npm install node-wit 
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-wit"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code E401

npm ERR! Registry returned 401 for GET on http://registry.npmjs.org/node-wit
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vcasari/Documents/projects_node/node-wit/npm-debug.log

Thanks a lot,
Vanni

**Comment by StillOnMyWay** [comment]
I've never experienced that problem, but the HTTP 401 error speaks to an authentication issue, as explained below. 

> There's a problem with 401 Unauthorized, the HTTP status code for authentication errors. And that’s just it: it’s for authentication, not authorization. Receiving a 401 response is the server telling you, “you aren’t authenticated–either not authenticated at all or authenticated incorrectly–but please reauthenticate and try again.” To help you out, it will always include a WWW-Authenticate header that describes how to authenticate.

The above originates at [http://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses](url)

What you can try to do is make sure the registry you're targeting is the correct, public domain one, and not a private one which you have no authorization for.

The most likely answer I found is the following.

`Remove .npmrc from your home directory` _found at _ [http://stackoverflow.com/questions/12657560/npm-install-gives-unauthorized-name-or-password-is-incorrect-error](url)

Hope this helps.
