### ISSUE TITLE
The documentation is a mess.

### ISSUE THREAD

**Issue by Yakito** [wit-ai/node-wit#47]
First of all, thanks for the library! Now... the documentation is a mess. Did I miss the announcement of all those major changes? Where were them announced (I am sure it was my fault)

I had everything set up for a launch, and now I have no idea how to adapt my old code (7 days old) with the new version of the library.

When trying to run my new code I get errors like this

`[wit] The 'goodbye' action should accept 1 argument: request. Learn more at https://wit.ai/docs/quickstart`

The problem is that when I go to that URL and check some examples, I see code like this:

```
getForecast({context, entities}) {
  return new Promise(function(resolve, reject) {
    var location = firstEntityValue(entities, "location")
    if (location) {
      context.forecast = 'sunny in ' + location; // we should call a weather API here
      delete context.missingLocation;
    } else {
      context.missingLocation = true;
      delete context.forecast;
    }
    return resolve(context);
  });
},
```

With 2 parameters

Also, where did say, merge, cb, sessionId, went? 

I will be more than happy to contribute with docs if that is what's needed. I think the project deserves it. 

Thanks again

**Comment by l5t** [comment]
Sorry for the mess. As you have noticed we are working on improving both the API and the docs (https://wit.ai/blog/2016/06/28/bot-engine-v1). In your example, you have only one argument that is a object {} containing context and entities. Hope this helps

**Comment by Yakito** [comment]
Thanks a lot, will rewrite my code now. Thanks again for the library
