### ISSUE TITLE
Getting syntax error

### ISSUE THREAD

**Issue by kenwen** [wit-ai/node-wit#48]
Getting the following syntax error when deploying an app

SyntaxError: Unexpected token {

/app/node_modules/node-wit/lib/wit.js:18

**Comment by akskap** [comment]
I stumbled across the same error. Updated node and it worked. You can try either of the two steps listed below:

1) Try executing the 'quickstart.js' file  '--harmony_destructuring' flag:

```
node --harmony_destructuring examples/quickstart.js <wit_token>
```

2) Fond your current version of NodeJS by typing:
`node --version`

If it is less than v6.2.2 then you can update NodeJS by using the following commands:

```
npm install -g n
n stable
```

Now if you execute:

`node --version`

It should confirm that you have an updated version installed.

Now try running the quickstart.js using:

`node examples/quickstart.js <Your wit token>`

**Comment by manuasir** [comment]
Same issue here. I'm using 6.2.2 version and still getting this error:
`SyntaxError: Unexpected token S in JSON at position 0
`

**Comment by manuasir** [comment]
Same issue here. I'm using 6.2.2 version and still getting this error when trying to execute quickstart.js:

`SyntaxError: Unexpected token S in JSON at position 0`
 `at Object.parse (native)`
 `at C:\..\node_modules\node-fetch\lib\body.js:43:15`
    `at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by akskap** [comment]
@manuasir 

Can you please post the script snippet causing this error ? Looks like it's caused by some other third party code rather than the default setup of wit.ai node sdk

**Comment by manuasir** [comment]
@akskap 

The code is exactly the same that 'basic.js' example in the repository

` 'use strict';

let Wit = null;
try {
  // if running from repo
  Wit = require('../').Wit;
} catch (e) {
  Wit = require('node-wit').Wit;
}

const accessToken = (() => {
  if (process.argv.length !== 3) {
    console.log('usage: node examples/basic.js <wit-access-token>');
    process.exit(1);
  }
  return process.argv[2];
})();

const actions = {
  send(request, response) {
    const {sessionId, context, entities} = request;
    const {text, quickreplies} = response;
    return new Promise(function(resolve, reject) {
      console.log('user said...', request.text);
      console.log('sending...', JSON.stringify(response));
      return resolve();
    });
  },
};

const client = new Wit({accessToken, actions});
client.interactive();

**Comment by ghost** [comment]
Yes, the original syntax error is solved by updating the local version of Node.  Line 18 of wit.js is a deconstruction, which is only supported in Node 6, not Node 4. (https://kangax.github.io/compat-table/es6/)

**Comment by ghost** [comment]
Also @manuasir , your parse error is because you have a comma after you close send(request, response).  You only need the comma if you are separating multiple actions.

**Comment by krjadhav** [comment]
Getting the following syntax error when deploying an app
SyntaxError: Unexpected token ,
\node-wit\examples\quickstart.js:58

**Comment by keshav787** [comment]
You need to upgrade node js to latest version , it worked for me 

for ubuntu : 

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by hoerlanton** [comment]
I wanted to get started with the Node.js SDK for Wit.ai. I followed the steps according to the comments in the messenger.js file:

// 1. npm install body-parser express request

// 2. Download and install ngrok from https://ngrok.com/download

// 3. ./ngrok http 8445

// 4. WIT_TOKEN=your_access_token FB_APP_SECRET=your_app_secret FB_PAGE_TOKEN=your_page_token node examples/messenger.js

// 5. Subscribe your page to the Webhooks using verify_token and https://<your_ngrok_io>/webhook as callback URL.

// 6. Talk to your bot on Messenger!

When I send a message to the server via Facebook messenger I receive the following error:

invalid json response body at https://f91805fe.ngrok.io/converse?session_id=2017-08-06T15%3A37%3A04.862Z&q=ldldl reason: Unexpected token T in JSON at position 0 invalid-son Oops! Got an error from Wit: Error at /Users/antonhorl/Documents/projekte-lokal/HotelMessenger/bots/node-wit-bot/node_modules/node-fetch/lib/body.js:49:31 at at process._tickCallback (internal/process/next_tick.js:188:7)

Has somebody any idea why? Thanks a lot for the effort.
