### ISSUE TITLE
QuickStart is broken

### ISSUE THREAD

**Issue by tm1000** [wit-ai/node-wit#49]
Followed the guide all the way through. https://wit.ai/docs/quickstart

Seems as though something is broken. I'm using the resources directly from git.

```
> how is the weather in Rome?
[wit] [Error: No 'getForecast' action found.]
```

**Comment by l5t** [comment]
You need to implement a getForecast action on your side also? If you reuse the quickstart.js example, it's here https://github.com/wit-ai/node-wit/blob/master/examples/quickstart.js#L43

**Comment by tm1000** [comment]
That's my point. I'm using the example IN this repo. It's already implemented.

```
[root@localhost node-wit]# node --harmony_destructuring examples/basic.js <key>
> how is the weather in Rome?
[wit] [Error: No 'getForecast' action found.]
```

**Comment by dezzzus** [comment]
Do you have created the getForecast action on wit.ai?
Please see this document.
https://wit.ai/docs/quickstart

**Comment by l5t** [comment]
Can you try to pull the latest version of the repo? I just did it and check with the quickstart app and it works

``` bash
 node examples/quickstart.js YOUR_TOKEN
> what's the weather in Paris
getForecast... {"forecast":"sunny in Paris"}
sending... {"text":"The weather will be sunny in Paris"}
>
```

**Comment by shad0wbeast** [comment]
@l5t  I am also facing the same issue...

**Comment by dezzzus** [comment]
@l5t Shall I help you
@shad0wbeast Please let me know your contact.
I can help you

**Comment by shad0wbeast** [comment]
Hey @alexdorn87  Thanks buddy.. you can contact me on skype : vaibhav.chorge1

**Comment by NoraKitchen** [comment]
I am also getting this error. Did you guys figure out what the issue was?

**Comment by tm1000** [comment]
I haven't bee able to try again but that's because when I constructed my own app (not using quick-start) everything worked fine. So I haven't had time to get back to it.

> Do you have created the getForecast action on wit.ai?

Yes. It was from this repo with no changes made. The function already existed in the code from this repository... with no changes made.

**Comment by NoraKitchen** [comment]
Ah, cool. Tried that myself now and got my own app to work fine as well. Guess it will remain forever a mystery.

> Yes. It was from this repo with no changes made. The function already existed in the code from this repository... with no changes made.

Same here. Tried it with no changes, and then when it didn't work also tried inserting my own custom action to see if it could find THAT action. That didn't work either. Just plain could not access any actions.

**Comment by michalbrcak** [comment]
I've had the same error and successfully fixed it. The problem was that name of my function in Wit.ai story included a space character " getForecast". Removing the space has fixed the problem.

**Comment by OrenBermeister** [comment]
Far too difficult

**Comment by sayeeguru** [comment]
hi all, i am trying now and code updated as per the doc.. i am facing following error 
Error: No 'getforecast' action found.
    at throwIfActionMissing (C:\ATTBOTS\node-wit\lib\wit.js:189:11)
    at runAction (C:\ATTBOTS\node-wit\lib\wit.js:194:3)
    at C:\ATTBOTS\node-wit\lib\wit.js:117:16
    at process._tickCallback (internal/process/next_tick.js:103:7)
