### ISSUE TITLE
Null actions

### ISSUE THREAD

**Issue by geckom** [wit-ai/node-wit#5]
node examples/weather.js <KEY>

> What's the weather?
> [error] No 'null' action found.

**Comment by brandonkovacs** [comment]
I am experiencing the same issue when following the tutorial

**Comment by patapizza** [comment]
Thanks, it should be fixed now.

**Comment by thegregthomp** [comment]
Did anyone figure out the cause of this? I'm getting it as well but not from the weather.js example.

**Comment by samcreate** [comment]
experiencing this on multiple apps. It's caused me to fork node-wit and check if the action is 'null' to skip over it so it doesn't crash my app.

**Comment by dougludlow** [comment]
I'm getting this as well...

**Comment by dougludlow** [comment]
I had to add a "null" action to mitigate the errors:

```
'null': ({sessionId, context, text, entities}) => {
      return Promise.resolve();
},
```

**Comment by filipdanic** [comment]
Having this issue as well.

**Comment by rohanar** [comment]
I have the same issue. Adding "null" action as @dougludlow mentioned did not solve the issue. I have the latest node-wit installed on Node-4.2.3. Running the basic.js example as:
node --use-strict --harmony_destructuring node_modules\node-wit\examples\basic.js <token>

**Comment by l5t** [comment]
thanks for reporting. We are looking

**Comment by melissamcewen** [comment]
this started happening to me only after I had created an action and then deleted it from both the app and my code. I think the issue is on the wit.ai end because when I deleted it and recreated it without the offending deleted action it worked.

**Comment by RobertoAlvarezCeballos** [comment]
Hi all,

This is happening on my test app as well. Keeps saying no null action found.

I'm using the latest version.

**Comment by melissamcewen** [comment]
So when I left work last night I was having issues with this. I come in this morning, nothing has changed, and it suddenly works. So unless elves are fixing my code while I'm at home, I think it might be a Wit.ai issue.

**Comment by tournage** [comment]
today as well i am seeing this issue.

**Comment by magnusburton** [comment]
Seeing this issue today

**Comment by lucaschain** [comment]
Seeing this issue today, what is the cause of this?

**Comment by magnusburton** [comment]
Seeing this issue today as well.

**Comment by MaximilianoGaitan** [comment]
Seeing this issue today

**Comment by fadlykayo** [comment]
did anyone know how to resolve this issue?

**Comment by AlexisNichel** [comment]
Help... did anyone know how to resolve this issue?

**Comment by lucaschain** [comment]
There is a temporary solution, as @dougludlow said, you can add a 'null' action like this:

```
'null': ({sessionId, context, text, entities}) => {
      return Promise.resolve();
},
```
Of course this is not a final nor recommended solution, but will stop errors from popping. You can even send the info parameters to some log file for further analysis to help solve the problem.

**Comment by gerasimos** [comment]
Hello,

I have the same problem using the latest code of `examples\messenger.js`. Where should I apply the workaround code proposed above?
