### ISSUE TITLE
TypeError from wit.js

### ISSUE THREAD

**Issue by evancloutier** [wit-ai/node-wit#50]
I recently implemented a new action for my bot and it is throwing the following error:

`Oops! Got an error from Wit:  TypeError: Cannot read property 'then' of undefined
    at /Users/username/Desktop/wit-test/node_modules/node-wit/lib/wit.js:110:40
    at process._tickCallback (internal/process/next_tick.js:103:7)`

I've done some digging and I'm not sure what the root issue is, here is the code that results in the error:

``` javascript
else if (json.type === 'action') {
     const action = json.action;
     throwIfActionMissing(actions, action);
     return actions[action](request).then((ctx) => {
               const nextContext = ctx || {};
               return this.converse(sessionId, null, nextContext).then(
                    continueRunActions(sessionId, message, nextContext, i - 1)
               );
     });
}`
```

**Comment by sdc-rafael** [comment]
you resolved it? thanks

**Comment by lexsoul** [comment]
I have the same issue

**Comment by lalomts** [comment]
Same over here. 😞

**Comment by evancloutier** [comment]
I ended up solving this problem - I believe that the code snippet above is looking for a promise within your code. In my case, the action I was trying to implement wasn't returning a promise properly, causing this error to be thrown. 

Apologies for not being more specific, but if you paste your code here I can try and help!

**Comment by lalomts** [comment]
Thanks for the help @evancloutier. I think this is the code block that might be causing the trouble. 

``` javascript
        Bot.getWit.runActions(
          sessionID,//the current session
          text, //the user's current message
          Bot.sessions[sessionID].context //the users current session state
        ).then((context)=> {
          console.log("Waiting for the  next user messages.");
          Bot.sessions[sessionID].context = context
        })
        .catch ((err) => {
          console.error("Oops! got an error from Wit", err.stack || err);
        });
```

**Comment by evancloutier** [comment]
``` javascript
Bot.getWit.runActions(
          sessionID, //the current session
          text, //the user's current message
          Bot.sessions[sessionID].context //the users current session state
        ).then((context) => {
```

Are you sure this is returning a callback? If you're sure it is, perhaps look at the actions you've implemented and ensure that the context being returned is properly being handled with promises.

I would also recommend to avoid using any Bot frameworks - there is a bit of a learning curve to using the Send API with Wit, but it prevents any miscommunications in your code because you don't know what is going on.

Hope that helps.
