### ISSUE TITLE
I can't access wit.ai service.

### ISSUE THREAD

**Issue by dezzzus** [wit-ai/node-wit#57]
I have inputted correct service token, But I can't access on it.
The response is only "Bad Auth".
It seems node-wit's problem.

**Comment by kennetham** [comment]
Possibly link to this? I observed that this issue from v3.3.2 to v4.0.0 had authentication issues. Possible regression.

https://github.com/wit-ai/node-wit/commit/3cd23274e5e22f452371024af4847af62655349a#commitcomment-19021749
