### ISSUE TITLE
Running into trouble while running the quickstart.js

### ISSUE THREAD

**Issue by hhietanen** [wit-ai/node-wit#59]
I was following the instructions on the 
https://wit.ai/docs/quickstart

When running the quick start and replacing the access token with a fresh Node v4.4.7:

> node examples/quickstart.js <wit-access-token>

I get: 

```
/Applications/MAMP/htdocs/wit/node-wit/examples/quickstart.js:36
    const {sessionId, context, entities} = request;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

**Comment by jl2l** [comment]
I am having this exact same issue.

The JS looks like it doesn't validate.

**Comment by hhietanen** [comment]
I tried running every example file in the folder, but none of them would launch with node. All had similar errors.

**Comment by jl2l** [comment]
I run jslint on the code in quickstart.js and i get

JSLint was unable to finish.
0.1Expected '"' and instead saw '''.
'use strict';
5.17Expected '"' and instead saw '''.
  Wit = require('../').Wit;
7.17Expected '"' and instead saw '''.
  Wit = require('node-wit').Wit;
10.24Expected 'function' and instead saw '=>'.
const accessToken = (() => {
12.17Expected '"' and instead saw '''.
    console.log('usage: node examples/quickstart.js ');
16.2Unexpected '('.
})();
21.44Expected 'function' and instead saw '=>'.
const firstEntityValue = (entities, entity) => {
30.25Expected '"' and instead saw '''.
  return typeof val === 'object' ? val.value : val;
38.19Expected '"' and instead saw '''.
      console.log('sending...', JSON.stringify(response));
44.6Expected 'let' and instead saw 'var'.
      var location = firstEntityValue(entities, 'location')
44.49Expected '"' and instead saw '''.
      var location = firstEntityValue(entities, 'location')
44.59Expected ';' and instead saw 'if'.
      var location = firstEntityValue(entities, 'location')
46.28Expected '"' and instead saw '''.
        context.forecast = 'sunny in ' + location; // we should call a weather API here
55.0Expected an identifier and instead saw '}'.
};

**Comment by jl2l** [comment]
@hhietanen something that i just figured out is make sure your npm is running 6+ of node, they don't show that but it requires 6+ and visual studio default is 4.2 I upgraded and those errors went away, still doesn't work but i think that was a culprit here.

**Comment by hhietanen** [comment]
After updating to Node 6.3. the issue was resolved and things started running. I was relying on the Node websites "works for most users" - installation instructions (which installs v4.4.7.) Thanks @jl2l .
