### ISSUE TITLE
firstEntityValue is not defined

### ISSUE THREAD

**Issue by commit-master** [wit-ai/node-wit#6]
Hello guys,

I'm a bit ashamed I can't even reproduce the QuickStart doc.. Anyway when I clone the repo, all I get into the index.js in the root is :

`module.exports = {
  Logger: require('./lib/logger.js').Logger,
  logLevels: require('./lib/logger.js').logLevels,
  Wit: require('./lib/wit.js').Wit,
}
`

And not what is written in the QuickStart doc. The code is actually in example/weather.js. So I do paste the merge code where it belongs :

`merge: (context, entities, cb) => {
    //Retrieve the location entity and store it into a context field
   const loc = firstEntityValue(entities, 'location');
   if(loc) {
     context.loc = loc;
   }
   cb(context);
  },
`

But I do get the following error in my terminal :
ReferenceError: firstEntityValue is not defined

Any ideas on how i could fix that and make it work ?
Thanks !

**Comment by molinto** [comment]
Exact same issue here, trying to follow this: https://wit.ai/docs/quickstart

**Comment by molinto** [comment]
Dreadful documentation & help, all over the place :(

Got mine to work like this (index.js):

```
'use strict';

const Wit = require('./lib/wit.js').Wit;

const firstEntityValue = (entities, entity) => {
    const val = entities && entities[entity] &&
            Array.isArray(entities[entity]) &&
            entities[entity].length > 0 &&
            entities[entity][0].value
        ;
    if (!val) {
        return null;
    }
    return typeof val === 'object' ? val.value : val;
};

const actions = {
    say: (sessionId, msg, cb) => {
        console.log(msg);
        cb();
    },
    merge: (context, entities, cb) => {
        //Retrieve the location entity and store it into a context field
        const loc = firstEntityValue(entities, 'location');
        if(loc) {
            context.loc = loc;
        }
        cb(context);
    },
    error: (sessionId, msg) => {
        console.log('Oops, I don\'t know what to do.');
    }
};


const client = new Wit('API_KEY_HERE', actions);
client.interactive();
```

**Comment by commit-master** [comment]
Working for me ! Thanks @molinto ! :+1:

**Comment by patapizza** [comment]
Thanks, we updated the Quickstart doc as well as the code in `examples/quickstart.js` accordingly.

Sorry about that!

**Comment by mikkhait** [comment]
Can you also update `examples/template.js` or documentation accordingly. It's missing the function `firstEntityValue`.

**Comment by patapizza** [comment]
`examples/template.js` doesn't need `firstEntityValue`. Where did you see that?

**Comment by joekim** [comment]
@patapizza Step #3 in the wi.ai quick start guide: https://wit.ai/docs/quickstart

It instructs the user to call firstEntityValue

```
 merge(sessionId, context, entities, message, cb) {
   // Retrieve the location entity and store it into a context field
   const loc = firstEntityValue(entities, 'location');
   if (loc) {
     context.loc = loc;
   }
   cb(context);
 },
```

**Comment by patapizza** [comment]
This is an extract of `examples/quickstart.js`, not `examples/template.js`. Am I missing something?

**Comment by Srinivas471** [comment]
@patapizza I'm getting syntex errors when running quickstart.js.. I don't know what's wrong in that .
could you plz help me out this

**Comment by b-najdenov** [comment]
@Srinivas471 , syntax errors would be fixed after updating node. Make sure the version of node is 6 or above

**Comment by mani541** [comment]
I am not able to get the quick replies sent from wit.Ai to say method. I am not using promises.
