### ISSUE TITLE
Error when I run quickstart.js file

### ISSUE THREAD

**Issue by Srinivas471** [wit-ai/node-wit#60]
C:\xampp\htdocs\BOT\node-wit-master>node examples/quickstart.js BQFCOQP2JB7HZLX2O4OXW6LRE3YELPQT
C:\xampp\htdocs\BOT\node-wit-master\examples\quickstart.js:36
    const {sessionId, context, entities} = request;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by jhernandezb** [comment]
The example uses ES6 features, which will depend on your node version or if you have to use something like babel.

**Comment by patapizza** [comment]
As @jhernandezme mentioned, it depends on the version of node you're running.
Two solutions:
1) update to latest node
2) run with the `--harmony_destructuring` flag, as explained in the README.

**Comment by Srinivas471** [comment]
I have the latest version only.
and that second option also I have Tried ,But nothing works for me

**Comment by nathgopi45** [comment]
Yeah , same here.. when i try to run with --harmony_destructuring flag, im getting the follwing exception
C:\hackathon\node-wit>node --harmony_destructuring examples/quickstart.js <wit-token>

> how is the weather in Rome?
> [Error: No ' getForecast ' action found.]

**Comment by keshav787** [comment]
You need to upgrade node js to latest version to fix this , i just did .

for ubuntu : 

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
