### ISSUE TITLE
X-Hub-Signature verification fails

### ISSUE THREAD

**Issue by jvannistelrooy** [wit-ai/node-wit#61]
Verifying Facebook Messenger's X-Hub-Signature fails in the messenger example. I fixed this in my own code by replacing the verification function with an example from Facebook's [graph-api-webhooks-samples](https://github.com/fbsamples/graph-api-webhooks-samples/blob/master/heroku/index.js). It uses  the express-x-hub library, which makes the code a bit cleaner in my opinion.

**Comment by harsh-rayzada** [comment]
how do you mean that it fails?
