### ISSUE TITLE
[wit] Max steps reached, stopping.

### ISSUE THREAD

**Issue by floooat** [wit-ai/node-wit#65]
After some time running quickstart.js, the server only responds with: "[wit] Max steps reached, stopping".

**Comment by l5t** [comment]
You can set the max step limit here:https://github.com/wit-ai/node-wit/blob/3cd23274e5e22f452371024af4847af62655349a/lib/wit.js#L9. This is a safety net to prevent infinite loop and it corresponds to the number of steps you can process before you get a type=stop

**Comment by perjerz** [comment]
What does it mean [wit] Max steps reached, stopping"?
