### ISSUE TITLE
Update documentation for using interactive

### ISSUE THREAD

**Issue by stopachka** [wit-ai/node-wit#72]
Now that latest master has a different api for using wit in interactive mode,  we should update our sdk to make this clearer.

**Comment by jainsourabh2** [comment]
I am facing below issue running on node 6.3.0 version. Are you talking about this issue? If yes, let me know whats the way to make it interactive?

client.interactive();
       ^

TypeError: client.interactive is not a function
    at Object.<anonymous> (/opt/nodejs/LnD/wit/node-wit/examples/quickstart.js:60:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

**Comment by joargp** [comment]
I have the same issue

**Comment by jainsourabh2** [comment]
I see that as part of the commit https://github.com/wit-ai/node-wit/commit/1dc3f28d4fe1dbd650c3a996b5b05c26908efe9d interactive function has been removed by @stopachka and moved into a separate file under lib folder i.e. interactive.js

**Comment by joargp** [comment]
For anyone else who just want to get it running, I put this in the bottom of quickstart.js

``` javascript
const client = new Wit({accessToken, actions});

const interactive = require('../lib/interactive');
interactive(client);
```

Thanks for the pointer @jainsourabh2

**Comment by jainsourabh2** [comment]
Thanks @joargp . I was about to work on this thread https://github.com/wit-ai/node-wit/issues/70 but you saved my time.

**Comment by humishum** [comment]
Just to point out

``` javascript
const interactive = require('../lib/interactive');
interactive(client);  
```

should replace

``` javascript
client.interactive();
```
