### ISSUE TITLE
quickstart.js error

### ISSUE THREAD

**Issue by malnosna** [wit-ai/node-wit#74]
I am following the Quick Start guide here: https://wit.ai/docs/quickstart
I tried to run the quickstart example

> node examples/quickstart.js <wit-access-token> (i put tried putting my wit token in, or leave it blank)

but I'm getting the same error:

```
const {sessionId, context, entities} = request;
      ^
```

> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3

I have already updated to the latest node.js v4.7.7 on my Windows 7 64-bit. What else am I missing?

**Comment by tareshss** [comment]
use the latest version v6.3.1. Might also have to add "use strict";

**Comment by malnosna** [comment]
I'm sorry, what do you mean by the latest version v6.3.1?  I cloned the node-wit from git yesterday, so I believe it's the latest version.  It also has "use strict" in the first line.

**Comment by tareshss** [comment]
go to https://nodejs.org/en/ . There are 2 download msi buttons. v4.7.7 LTS and v6.3.1 Current.

**Comment by malnosna** [comment]
Updated to v6.3.1 and now it gives this error:

> node-wit\examples\quickstart.js:59
> client.interactive();
>        ^
> 
> TypeError: client.interactive is not a function
>     at Object.<anonymous> (node-wit\examples\quickstart.js:59:8)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.runMain (module.js:575:10)
>     at run (bootstrap_node.js:352:7)
>     at startup (bootstrap_node.js:144:9)
>     at bootstrap_node.js:467:3

What else could be wrong?

**Comment by Thomas0c** [comment]
See #72 for details and a potential fix.

**Comment by malnosna** [comment]
Thanks @Thomas0c. That works!

**Comment by keshav787** [comment]
You need to upgrade node js to latest version , it worked for me 

for ubuntu : 

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
