### ISSUE TITLE
How do I actually integrate this app with Facebook Messenger's API to create a chatbot?

### ISSUE THREAD

**Issue by ninajlu** [wit-ai/node-wit#8]

**Comment by patapizza** [comment]
Hi Nina,

We haven't released any examples showing an integration with the Messenger API yet. In the meantime, please refer to their documentation: https://developers.facebook.com/docs/messenger-platform/quickstart

From a high level, you want to call `.runActions()` for each user message, and forward your bot response within your `say` action.

Hope this helps.

**Comment by patapizza** [comment]
I just updated the README with basic instructions on how to do that.
The example code is in `examples/messenger.js`.

**Comment by DiegoRBaquero** [comment]
I put up a simple wrapper if anyone is interested [fb-messenger](https://github.com/DiegoRBaquero/node-fb-messenger)
