### ISSUE TITLE
Calling last Action instead of others Action

### ISSUE THREAD

**Issue by AyeChanPyaeSone** [wit-ai/node-wit#81]
I am now using messenger.js to connect facebook messenger. So there is four functions I added in wit.ai 
1. \- getContact
2. -getFlight
3. -getEmergencyContact

After I call in getFlight action, I connect with my REST API then return context. After that all the actions are not working and then returned me **getFlight** context. is it because there is something  wrong with context? how can i clear context variable?

**Comment by cisnky** [comment]
@AyeChanPyaeSone Delete the attribute from the context after you have finished with it. Wit uses the context to understand what you want to do.

**Comment by stopachka** [comment]
@cisnky is right :)
