### ISSUE TITLE
Syntax Error in lib/wit.js:3 Unexpected token. See attachment.

### ISSUE THREAD

**Issue by v-adhithyan** [wit-ai/node-wit#83]
![screen shot 2016-08-22 at 8 53 00 pm](https://cloud.githubusercontent.com/assets/14884935/17860280/86dd89b2-68aa-11e6-984d-5be31d550cb1.png)

**Comment by praducg** [comment]
Hi Adithya,

I also faced same issue I upgraded node to latest version and fixed the
issue.
Do check stack workflow as well.

All the best.
Regards
Pradeep

**Comment by praducg** [comment]
Check with  node --harmony_destructuring index.js

As well

**Comment by v-adhithyan** [comment]
@praducg : Thanks pradeep 👍 .
