### ISSUE TITLE
Context is always empty

### ISSUE THREAD

**Issue by raghunathj** [wit-ai/node-wit#85]
I am using messenger.js and i have a custom action called fetchlocation. I first do a merge before i trigger fetchlocation, but always the context is empty for me to access the location identified by wit.ai Is there a example story and custom actions example for fb messenger

**Comment by l5t** [comment]
Have you checked the example from this recipe? https://wit.ai/docs/recipes#integrate-with-facebook-messenger

**Comment by raghunathj** [comment]
I tried both the messenger.js example as well. I am trying to get the intents that wit has identified in a action but the method accepts only session ID and context but no entities. So I don't have data to perform some action.

**Comment by l5t** [comment]
getForecast({context, entities}) is an example of how to get the entities. Look at the quickstart js example

**Comment by raghunathj** [comment]
but the example file it looks very different, especially in messenger.js example

**Comment by timigod** [comment]
Context is always undefined

**Comment by stopachka** [comment]
hey everyone, to get the context to be some object, you need to pass it in as one in wit.runActions

```
wit.runActions(
  sessionId, 
  text, 
  context // this should be some object -- i.e {}
);
```
