### ISSUE TITLE
Does not work with AWS Lambda: Unexpected token {

### ISSUE THREAD

**Issue by markdesign** [wit-ai/node-wit#88]
```
"errorMessage":"Unexpected token {",
"errorType":"SyntaxError",
"stackTrace":["Module._compile (module.js:373:25)",
"Object.Module._extensions..js (module.js:416:10)",
"Module.load (module.js:343:32)",
"Function.Module._load (module.js:300:12)",
"Module.require (module.js:353:17)",
"require (internal/module.js:12:17)",
"Object.<anonymous> (/var/task/node_modules/node-wit/index.js:3:8)",
"Module._compile (module.js:409:26)",
"Object.Module._extensions..js (module.js:416:10)"]}"
```

Solution for now is to use node-wit@3.3.2

**Comment by dannycohn** [comment]
Is this still an issue? Any way around it?

**Comment by markdesign** [comment]
I might have to run it through babel or something to compile down to ES5 to work in lambda.

**Comment by dougsilkstone** [comment]
Confirmed fix - Compile interactive.js and wit.js to ES5 using https://babeljs.io/repl/ or similar in the meantime.

First ever Git post.  Glad to be onboard.

**Comment by l5t** [comment]
Sorry for the late reply. Indeed Babel is a good solution. Another one here: http://stackoverflow.com/questions/30254090/is-there-a-way-to-run-es6-components-specifically-promises-and-generators-in-a

**Comment by timgshi** [comment]
@dougsilkstone I still can't get it to work. Do you have a repo with it up?

**Comment by dougsilkstone** [comment]
Negative @timgshi - I ended up using Harmony mode with heroku to allow ES6 functioning - I did find Apex, that allows you to transform / deploy ES6/7 code on Lambda - with an example https://github.com/apex/apex and https://github.com/apex/apex/tree/master/_examples/babel-webpack respectively.

**Comment by laardee** [comment]
Hi, @l5t are you planning to keep the module ES6 only? I forked the repo and compiled it with Babel to get it work with my AWS Lambda/Serverless Framework project. 

Here is the fork: https://github.com/laardee/node-wit. The compiled code is in bin folder which is used in index.js, examples uses ES6 code like before. I can open a PR if you wish to support legacy node versions this way.

I bet that AWS is not upgrading node version which AWS Lambda uses for a while - latest upgrade to version 4.3.2 was in last April :-)

I think this issue is related to issue https://github.com/wit-ai/node-wit/issues/69.

**Comment by l5t** [comment]
cc @blandinw

**Comment by timgshi** [comment]
@laardee did you have to do anything else to get it to work? I just tried using your library and unfortunately still getting import errors.

**Comment by laardee** [comment]
@timgshi, I just required my fork in package.json

```
"dependencies": {
  "node-wit": "git+https://github.com/laardee/node-wit.git",
```

then used the Wit in my Lambda code 

```
'use strict';

const Wit = require('node-wit').Wit;

....

const client = 
  new Wit({
    accessToken: process.env.WIT_AI_TOKEN,
    actions: {
      send: (request, response) => new Promise((resolve, reject) ... 

```

**Comment by wallali** [comment]
I am using node 4.4.7 and get this same issue. I think it is a little too early for this library to start adopting features still in beta for node as many developers could be using the LTS node release.

**Comment by ikornienko** [comment]
There is also kind of misleading statement in package.json

``` json
  "engines": {
    "node": ">=4.0.0"
  }
```

since one cannot use/run it with node 4.x as concluded in this discussion.

**Comment by laardee** [comment]
I opened a PR that adds support for using node-wit as a library with older node versions https://github.com/wit-ai/node-wit/pull/95 @l5t or @blandinw care to take a look?

**Comment by jsfour** [comment]
Is there still a need for a PR for this? Im happy to help.

**Comment by laardee** [comment]
@jsmootiv, the PR just got merged yesterday :smile: next time the package is published to npm it will be compatible with older node versions.

**Comment by stopachka** [comment]
Indeed, thanks @laardee for the hard work. Look for a new version to be published next week

**Comment by manoharreddyporeddy** [comment]
I had a similar error.
It worked with nodejs6.10 when I set it manually in lambda.
