### ISSUE TITLE
Syntax Error while running the Examples. 

### ISSUE THREAD

**Issue by PraveenkumarDonga** [wit-ai/node-wit#94]
![wit_error1](https://cloud.githubusercontent.com/assets/8088246/19728129/d8162040-9baf-11e6-8e97-0d0de7813778.png)

I am trying to run the examples but I am getting the above error.
So Could any one please help me with this Error.

npm -v  : 2.15.1
node -v :v0.10.48

Thanks in Advance.

**Comment by ikornienko** [comment]
Yeah, with node v0.10.48 it won't fly. From README.md you may see

``` shell
# Node.js <= 6.x.x, add the flag --harmony_destructuring
node --harmony_destructuring examples/basic.js <MY_TOKEN>
# Node.js >= v6.x.x
node examples/basic.js <MY_TOKEN>
```

so upgrade to v6.x.x should help. Also see somewhat related #88 (which basically is about not being able to use it with node v4.3.2)

**Comment by PraveenkumarDonga** [comment]
Hi! ikornienko,
Thanks, it is working.
